language: python
sudo: false
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9


cache:
  directories:
    - $HOME/.cache/pip

services:
  - MySQL
  - PostgreSQL

env:
  - DJANGO=3.0 DRF=3.11
  - DJANGO=3.0 DRF=3.12

  - DJANGO=3.1 DRF=3.11
  - DJANGO=3.1 DRF=3.12

install:
  - pip install tox "coverage<=4.0" python-coveralls>=2.5 coveralls>=0.5 codecov

script:
  - tox -e "py${TRAVIS_PYTHON_VERSION//.}-d${DJANGO//.}-drf${DRF//.}"

before_success:
  - coverage erase

after_success:
  - coverage combine
  - codecov
